### ISSUE TITLE
check hook fails in 1.9.0 without having previously used service discovery feature

### ISSUE THREAD

**Issue by thomasmitchell** [genesis-community/cf-genesis-kit#107]
It tries to migrate the service discovery certificates and fails if it can't find them at
https://github.com/genesis-community/cf-genesis-kit/blob/a0803cfcf89db799aef70153788c5e5b0bd5b5ea/hooks/check#L115

But if you've never used the service discovery feature, those certs shouldn't be there.

**Comment by thomasmitchell** [comment]
also, it doesn't give any error message when this happens. Just says "environment files [FAILED]"

**Comment by dennisjbell** [comment]
That is contrary to the intention or experience that I had -- I will look into this.

**Comment by dennisjbell** [comment]
Issue introduced when relocating certs was refactored due to PR review - fixing, and posting new release.

**Comment by dennisjbell** [comment]
Fixed in release 1.9.1
