### ISSUE TITLE
undocumented: locket server certificate needs to be regenerated in 1.9.0

### ISSUE THREAD

**Issue by thomasmitchell** [genesis-community/cf-genesis-kit#108]
It needs to be trusted for 127.0.0.1

**Comment by dennisjbell** [comment]
This was documented in the release notes under "Upgrade Notes": https://github.com/genesis-community/cf-genesis-kit/releases/tag/v1.9.0

**Comment by dennisjbell** [comment]
Updated the release notes in a more explicit way.
