### ISSUE TITLE
route service is not enabled successfully 

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/cf-genesis-kit#125]
The following commit removed the `router.route_services_secret` property from the gorouter job and added the same property under the cloud_controller_ng job.
https://github.com/genesis-community/cf-genesis-kit/commit/b88090a29a0bd5df7f673390ecc874a427392662

In this case, after binding route service, when we tried to use the servive, a 502 error is returned. 

In our test, we found out that the `router.route_services_secret` needs to be configured for both the gorouter and cloud_controller_ng job to make route service work. '

The spec for both jobs  are as follows
https://github.com/cloudfoundry/routing-release/blob/develop/jobs/gorouter/spec#L160-L162
https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec#L953-L955

**Comment by thomasmitchell** [comment]
closed by #126
