### ISSUE TITLE
for v2.0.0 branch - not validating vm_extensions in genesis

### ISSUE THREAD

**Issue by thomasmitchell** [genesis-community/cf-genesis-kit#133]
Task 174863 | 18:45:59 | Error: The vm_extension 'diego-ssh-proxy-network-properties' has not been configured in cloud-config.

**Comment by 7hunderbird** [comment]
👍

**Comment by 7hunderbird** [comment]
Got the same thing.

**Comment by dennisjbell** [comment]
Fixed in release [v2.0.2](https://github.com/genesis-community/cf-genesis-kit/tree/v2.0.2) via updated MANUAL.md
