### ISSUE TITLE
Migration of existing CF production environment to v2 using genesis kits

### ISSUE THREAD

**Issue by lordcf** [genesis-community/cf-genesis-kit#14]
Hi Team,

We are planning to move our production environment to bosh 2.0 deployments. Currently we have CF  v281 deployed using genesis v1 . We are investigating on how current deployment can be moved to bosh v2 using genesis v2 (kits). In cf-deployment repo, community has provided with transition scripts from v1 to v2. We are currently using shield to backup CF 

While adopting genesis v2 for  CF deployment, is their any strategy into genesis or kits to migrate existing deployments?

**Comment by jhunt** [comment]
That's a tricky one.  The Kits have each undergone some structural changes as approaches in the Cloud Foundry community have changed (i.e. cf-deployment, bosh-deployment, etc.)

We are working on a "none" kit that will allow you to _source in_ your existing v1 manifests, as you work on a migration by hand.

Another approach we have used is a full teardown / rebuild using backups (vis. [SHIELD](https://github.com/shield)) to "migrate" data from an old v1 CF to a new v2 CF.

Another option would be to build out new deployment manifests using v2 kits, migrate your vaulted creds to their new locations, and keeping overriding things in your env file until you get a manifest that isn't so churny.

**Comment by lordcf** [comment]
We have tried migration using MySQLdump tool. But if are not able to login into cf after migrating data from old v1 CF to new v2 CF using cf-deployment repo provided by community.
CF v1 version => 283
cf-deployment => 1.20.0
Is there any schema change or would this be appropriate to migrate using MySQL tools for migration?

Also for using shield as an option, can we directly use current shield to restore on CF deployment using genesis?

Current v1 deployments version:-
- CF v283 (without TLS enablesd)
- shield v6.6.5

Thanks and Regards 
Cibaca 
Atos Cloud Foundry

**Comment by jhunt** [comment]
were you using https://github.com/starkandwayne/cf-deployment as a base and are you moving to https://github.com/genesis-community/cf-genesis-kit?

**Comment by lordcf** [comment]
We are currently using genesis v1 as a base. Now we want to migrate it to bosh 2.0 and want to move to (https://github.com/genesis-community/cf-genesis-kit). We also want all our data for users and application to be migrated to CF deployed using genesis kits.  Currently we are thinking if below two options 

1. Migrating individual databases using MySQL dump. Here we want to use cf-genesis-kit for bosh 2.0.   Currently I tried migration CF v283 (Without mtls ) v1 deployment to cf-deployment (1.20.0 , not used genesis kit yet just wanted to see if i can migrate databases). But it failed, users were not able to login. Wanted to know if directly i can migrate using MySQL dump or there may be any schema changes. 

2. Using shield to migrate CF data, but for our v1 deployments we have 6.6.5 version used. So do i first need to upgrade and then try migration to cf-genesis-kits deployment?

**Comment by jhunt** [comment]
@dennisjbell and I put our heads together and came up with https://github.com/starkandwayne/genesis/issues/262, which is slated for v2.7 (we're in the final stages of releasing 2.6 GA)
