### ISSUE TITLE
JQ error when building manifest

### ISSUE THREAD

**Issue by Mwilloughby1982** [genesis-community/cf-genesis-kit#15]
First time using genesis on a cf deployment anyone ever seen this. 

jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
. |= (.[] |= (.values[] |= (if .skip_ssl_validation == false then .skip_ssl_validation = true else . end ))

Does this right after Certs regardless if i enter my own certs or have it generate them.

**Comment by jhunt** [comment]
What version of jq?

**Comment by Mwilloughby1982** [comment]
jq-1.5-1-a5b5cbe

**Comment by jhunt** [comment]
I've never seen that error myself, but I do know that we are going to be removing the jq-y bits from all kits, since we have better alternatives that aren't as obtuse / dense.

**Comment by Mwilloughby1982** [comment]
this is right after i put in the certs and it even happens if i have genesis auto generate the certs. 

It is almost as iff this line is breaking.... which is the line on the error in the genesis executable 
This is line 2015 of the genesis app     decode_json(join("\n",@json));$

**Comment by jhunt** [comment]
Is this fixed by #18 for you?

**Comment by Mwilloughby1982** [comment]
This has been fixed and merged.
