### ISSUE TITLE
Bump up release versions to prevent breaking changes

### ISSUE THREAD

**Issue by naveedahd** [genesis-community/cf-genesis-kit#152]
A few of the releases included as part of the upstream/canonical `cf-deployment` have problematic versions. They should be bumped to the stable versions which include the bug fixes. 

1. CAPI release should be bumped from 1.90 to 1.91
Issue with 1.90: 
[Github Issue](https://github.com/cloudfoundry/cloud_controller_ng/issues/1555)
[CF Slack](https://cloudfoundry.slack.com/archives/C0FAEKGUQ/p1581635589161800)
[1.91 release notes](https://github.com/cloudfoundry/capi-release/releases/tag/1.91.0)

2. UAA release should be bumped from 74.13 to 74.15
[Issue with 74.13](https://www.pivotaltracker.com/n/projects/997278/stories/171289320)
[74.15 release notes](https://github.com/cloudfoundry/uaa-release/releases/tag/v74.15.0)

3. loggregator release should be bumped from 106.3.8 to 106.3.11
[Issue with 106.3.x](https://github.com/cloudfoundry/loggregator-release/issues/401)
[106.3.11 release notes](https://github.com/cloudfoundry/loggregator-release/releases/tag/v106.3.11)
[106.3.10 release notes](https://github.com/cloudfoundry/loggregator-release/releases/tag/v106.3.10)
This fix has been tested at a couple of client sites and it works. loggregator release v106.3.11 coupled with loggregator-agent-release 5.3.8 and bosh-dns 1.24.0 works perfectly.

4. loggregator-agent-release should be bumped from 5.3.6 to 5.3.8
This has also been tested at different sites and works fine.

**Comment by ramonskie** [comment]
this should be done by getting new cf-deployment version

**Comment by naveedahd** [comment]
@ramonskie Sure. Thanks
