### ISSUE TITLE
CF deployment > 12.44 fails because `route_registrar` job can't find NATS servers

### ISSUE THREAD

**Issue by naveedahd** [genesis-community/cf-genesis-kit#154]
When deploying CF kit 2.0.0, the deployment fails with the following error:

```
Task 5071 | 20:51:48 | Updating instance uaa: uaa/768ca67f-0b0f-4969-b208-f3454146a4cd (0) (canary) (00:24:08)
                     L Error: 'uaa/768ca67f-0b0f-4969-b208-f3454146a4cd (0)' is not running after update. Review logs for failed jobs: route_registrar
Task 5071 | 21:15:56 | Error: 'uaa/768ca67f-0b0f-4969-b208-f3454146a4cd (0)' is not running after update. Review logs for failed jobs: route_registrar
```

Job's logs on the failing UAA VM located at `/var/vcap/sys/log/route_registar/route_registrar.stdout.log` show the following:
```
{"error":"nats: no servers available for connection","nats-hosts":["nats-0:4222"]}} 
```
This is because starting from `cf-deployment v12.44`, NATS hostname is used instead of the IPs. 
Reference: https://github.com/cloudfoundry/cf-deployment/pull/877

As we're tracking the upstream for `cf-deployment`, we had the DNS aliasing for NATS in the `cf-deployment.yml` but we need to add it to the `operations/rename-network-and-deployment.yml` file too. (The Genesis compliant ops file)

**Comment by ramonskie** [comment]
resolved in https://github.com/genesis-community/cf-genesis-kit/commit/871689e3552148dc16cb856e5f977daf639e5150
