### ISSUE TITLE
Job 'consul_agent' not found in Template table

### ISSUE THREAD

**Issue by lordcf** [genesis-community/cf-genesis-kit#25]
We are deploying CF using cf-genesis-kit v0.3.1. While deploying CF, we are getting below error:
`
Task 6079 | 10:18:44 | Preparing deployment: Preparing deployment (00:00:00)
                     L Error: Job 'consul_agent' not found in Template table
Task 6079 | 10:18:44 | Error: Job 'consul_agent' not found in Template table
`
We have tried some lower versions of cf-genesis-kit,  but from kit v0.1.13 this issue is faced
Is there any configuration or property to be added in consul job for above error?

**Comment by jhunt** [comment]
What does `bosh inspect-release consul/181` say?
