### ISSUE TITLE
parameterize system_domain and apps_domains

### ISSUE THREAD

**Issue by 7hunderbird** [genesis-community/cf-genesis-kit#31]
When attempting to use `system_domain` to modify the system domain from from default to alternate value we have it documented that a user can provide a this value, but it does not change anything yet.

---

We are checking for the `system_domain` and `apps_domains` as pre-flight checks (hooks/check) before deploying, but if a user chooses to not use the defaults the checks will fail.

We need to put in the params for `system_domain` and `apps_domains`.   Also pay attention to the idea that apps_domains can be a list of items.

**Comment by jhunt** [comment]
The only time the CF kit preflights the base_domain is if the `haproxy` and `tls` features are on.  In that case, you probably ought not muck about with the app and system domains, and just rely on the kit to construct them for you, from the base_domain.

If you have strong opinions on domain names, you are assumed to have strong opinions on load balancers and SSL termination as well, from a maturity standpoint.  For getting started with CF and Genesis, or for running labs, demos, sandboxen, the defaults (with self-signed certs from the `self-signed` feature) should be sufficient.

I don't think we should change anything about the kit as it relates to this issue.
