### ISSUE TITLE
express how many IP addresses required

### ISSUE THREAD

**Issue by 7hunderbird** [genesis-community/cf-genesis-kit#32]
When a kit can check for how many IP addresses are required in order to run.  If possible make it clear that we need dynamic IP addresses vs static vs reserved, that is, which type.

This will help nudge the user in the right direction of helping to setup their network IP allocations.

```
Failed to reserve IP for 'consul_etd/asdfasdf-asdf-sdfas-asdf-2330942342234234 (0)' for manual network
```

**Comment by jhunt** [comment]
This is now documented on genesisproject.io, where we lay out sizing recommendations for both Operations Tier and Cloud Foundry instnces.
