### ISSUE TITLE
Fix Diego/Silk/Locket postgres conneciton string

### ISSUE THREAD

**Issue by ChrisMcGowan** [genesis-community/cf-genesis-kit#38]
Current gen of the kit (v1.1.1 as of this issue) is using the value of `postgres` for db_schema where those CF jobs are using the `postgres` database for their DB stores and not there respective databases.

**Comment by Proplex** [comment]
This was fixed as of v1.2.0 (PR #40)

There is a Genesis Migration Process (GMP) assigned to this issue, [GMP-CF0001](https://www.genesisproject.io/docs/migrations/gmp-cf-0001/). Versions affected by this bug are v1.1.0, v1.1.1, and v1.1.2. If you deployed a CF with any of those versions, please read the guide (linked above) on how to resolve the issue before upgrading to v1.2 or beyond.
