### ISSUE TITLE
Issue when using 'autoscaler' and 'migrate-1.3-without-consul' feature flags.

### ISSUE THREAD

**Issue by elric392** [genesis-community/cf-genesis-kit#47]
When trying to do a 'genesis deploy <env>' for the CF kit (v1.4.0), where we specified the 'autoscaler' and 'migrate-1.3-without-consul' feature flags, we ran into an issue.  After generating the manifest and saying 'y' to continue, we got this error almost immediately.

Task 111 | 13:32:40 | Preparing deployment: Preparing deployment (00:00:02)
                   L Error: Cannot tell what release template 'eventgenerator' (instance group 'as-collector') is supposed to use, please explicitly specify one

We removed the 'autoscaler' feature flag and are able to deploy.

**Comment by jhunt** [comment]
Should be fixed with #49 ; will be available in a 1.4.1 release soon

**Comment by jhunt** [comment]
This was made available in 1.4.1.
