### ISSUE TITLE
Static IPs are not 'stripped' across AWS AZs

### ISSUE THREAD

**Issue by elric392** [genesis-community/cf-genesis-kit#48]
During an initial test session, using the CF Kit v1.4.0 (and the latest Vault Kit), we ran into the requirement for **_static IPs_** to be specified in the cloud-config.  Several thoughts/concerns arose from this .... particularly with regards to use in AWS (and likely GCP/Azure).

- Why are static IPs even required?
            When you are using external LBs requiring VM extensions.
            When you have BOSH DNS.
- All 'HA' capabilities are essentially lost, since the static IPs are not stripped across the AZs.
           (ie .... deployed 2 routers and both are allocated in AZ1 .... none in AZ2 or AZ3)

**Comment by jhunt** [comment]
We are no longer using static IPs (as of the forthcoming 1.6.1 release), so this issue should "resolve" itself accordingly.

**Comment by dennisjbell** [comment]
This has been resolved by dropping static IPs.
