### ISSUE TITLE
Add routing-api

### ISSUE THREAD

**Issue by dennisjbell** [genesis-community/cf-genesis-kit#55]
As per https://github.com/cloudfoundry/cf-deployment/commit/791d60104

**Comment by tjliebel** [comment]
I believe this was completed by Tom and me in #96 and released in v1.7.2

**Comment by jhunt** [comment]
@dennisjbell can you double-check on this this week?

**Comment by dennisjbell** [comment]
I also believe it was done and I will close this out once I absolutely
verify.
