### ISSUE TITLE
Investigate moving smoke-tests to a pre-existing instance_group

### ISSUE THREAD

**Issue by jhunt** [genesis-community/cf-genesis-kit#64]

**Comment by dennisjbell** [comment]
Tried moving it to api, but this caused the tests to take at a minimum twice as long to run, erasing any gains from not booting a separate VM.  Instead, moved to uaa instance which worked well.

As there are multiple UAA instances, the instance has to be specified when running the test, which is not currently the norm, so to facilitate this change, wrapped the smoke test call as a genesis addon (it also gets rid of the ambiguity of hyphen vs underscore):

```
genesis do <env> -- smoketest
```
This is a simple wrapper for 
```
$GENESIS_BOSH_COMMAND -e $BOSH_ENVIRONMENT -d $BOSH_DEPLOYMENT run-errand smoke_tests --instance uaa/first
```

**Comment by dennisjbell** [comment]
This was handled in v1.x line, but made defunct by moving to upstream cf-deployment layout for v2.x line
