### ISSUE TITLE
Investigate consolidation of jobs on fewer VMs

### ISSUE THREAD

**Issue by jhunt** [genesis-community/cf-genesis-kit#67]
We have historically been divergent from cf-deployment (because we came first, and they didn't take any direction from us when they wrote their configuration).

It's time to take another look at cf-deployment and see if they have any neat tricks up their sleeves for corralling CF on fewer VMs (even in the non-small-footprint model).

Attached are two summary YAMLs that extract information on instance groups and their constituent jobs, for both a cf-deployment (with no additional ops files activated) and a Genesis CF.

[cf-deployment-instance-groups.yml.txt](https://github.com/genesis-community/cf-genesis-kit/files/3631905/cf-deployment-instance-groups.yml.txt)
[genesis-cf-instance-groups.yml.txt](https://github.com/genesis-community/cf-genesis-kit/files/3631906/genesis-cf-instance-groups.yml.txt)

**Comment by jhunt** [comment]
(for posterity, here's the command I ran to generate these, assuming `manifest.yml` is either the root `cf-deployment.yml` file from cf-deployment, or a full BOSH manifest from a Genesis-deployed CF:)

```
spruce json manifest.yml  | \
  jq -r '{instance_groups: [.instance_groups[] | {name: .name, zjobs: [.jobs[] | (.release + "/" + .name)] }]}' | \
  spruce merge | \
  sed -e 's/^  zj/  j/'
```

**Comment by dennisjbell** [comment]
as we're moving to matching cf-deployment in its entirety, this ticket is moot.
