### ISSUE TITLE
Make Postgres max_connections configurable through params in subkit

### ISSUE THREAD

**Issue by thomasmmitchell** [genesis-community/cf-genesis-kit#8]
Defaults to 100 through Postgres defaults. Should be configurable, as a scaling deployment usually needs more.

**Comment by Proplex** [comment]
Support was added in 470da792d1153faf3fbcc4431008cc4bdb24ce2f. Will document shortly.

**Comment by jhunt** [comment]
Handled in https://github.com/genesis-community/cf-genesis-kit/commit/775c7629197bfe4f1c3ea02cf4fee4b1fc575f2a
