### ISSUE TITLE
BOSH DNS is not working on App Containers

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/cf-genesis-kit#84]
When we ssh to an app, the `etc/resolve.conf` is populated with `169.254.0.2` and your internal DNS server configured in your manifest. BOSH DNS server `169.254.0.2`  is not reachable by app container, `dig @169.254.0.2 google.com` will fail. When your internal DNS can not resolve google.com on your container, your app can not talk with outside of the world.

On the app container, BOSH DNS needs to be enabled as default DNS server.

**Comment by jhunt** [comment]
This has been reworked in #89, and works great in a variety of tested circumstances.
